name: Python Hello World Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.14

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Hello World App
      run: python app.py
